KlinikApp_WebApplication3/Models/Patient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinikApp_WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Examinations = new HashSet<Examination>();
        }
    
        public int Pat_Id { get; set; }
        public string P_Lastname { get; set; }
        public string P_Firstname { get; set; }
        public Nullable<System.DateTime> P_Birthday { get; set; }
        public string P_Address { get; set; }
        public Nullable<int> P_Plz { get; set; }
        public string P_Bundesland { get; set; }
    
        public virtual Bundesland Bundesland { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
    }
}

KlinikApp_WebApplication3/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KlinikApp_WebApplication3.Models;

namespace KlinikApp_WebApplication3.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private KlinikDbEntities db = new KlinikDbEntities();

        // GET: Patients
        //public ActionResult Index(string searchPatient)
        //{
        //    ViewBag.suchstring = searchPatient;
        //    var patients = db.Patients.Include(p => p.Bundesland);
        //    if(!String.IsNullOrEmpty(searchPatient))
        //    {
        //        patients = patients.Where(p => p.P_Firstname.StartsWith(searchPatient) || p.P_Lastname.StartsWith(searchPatient));
        //    }
        //    return View(patients.ToList());
        //}

        public ActionResult Index()
        {
            var patients = db.Patients.Include(p => p.Bundesland);
            return View(patients.ToList());
        }

        public ActionResult PatientSearch(string searchPatient, string sortOrder)
        {
            ViewBag.patientsearch = searchPatient;
            ViewBag.LastnameSortParm = String.IsNullOrEmpty(sortOrder) ? "ln_desc" : "";
            ViewBag.FirstnameSortParm = String.IsNullOrEmpty(sortOrder) ? "fn_desc" : "fn";
            var patients = db.Patients.Include(p => p.Bundesland);
            if (!String.IsNullOrEmpty(searchPatient))
            {
                patients = patients.Where(p => p.P_Firstname.StartsWith(searchPatient) || p.P_Lastname.StartsWith(searchPatient));
            }
            switch (sortOrder)
            {
                case "ln_desc":
                    patients = patients.OrderByDescending(p => p.P_Lastname);
                    break;
                case "fn":
                    patients = patients.OrderBy(p => p.P_Firstname);
                    break;
                case "fn_desc":
                    patients = patients.OrderByDescending(p => p.P_Firstname);
                    break;
                default:
                    patients = patients.OrderBy(p => p.P_Lastname);
                    break;
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_patients", patients.ToList());
            }
            return View("Index", patients.ToList());
        }

        // GET: Patients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: Patients/Create
        public ActionResult Create()
        {
            ViewBag.P_Bundesland = new SelectList(db.Bundeslands, "B_Id", "B_Name");
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Pat_Id,P_Lastname,P_Firstname,P_Birthday,P_Address,P_Plz,P_Bundesland")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.P_Bundesland = new SelectList(db.Bundeslands, "B_Id", "B_Name", patient.P_Bundesland);
            return View(patient);
        }

        // GET: Patients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            ViewBag.P_Bundesland = new SelectList(db.Bundeslands, "B_Id", "B_Name", patient.P_Bundesland);
            Session["sessionPatientId"] = patient.Pat_Id;
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "P_Lastname,P_Firstname,P_Birthday,P_Address,P_Plz,P_Bundesland")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                patient.Pat_Id = (int)Session["sessionPatientId"];
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                Session["sessionPatientId"] = null;
                return RedirectToAction("Index");
            }
            ViewBag.P_Bundesland = new SelectList(db.Bundeslands, "B_Id", "B_Name", patient.P_Bundesland);
            return View(patient);
        }

        // GET: Patients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KlinikApp_WebApplication3/Views/Patients/Create.cshtml
@model KlinikApp_WebApplication3.Models.Patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.P_Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Plz, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Plz, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Plz, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Bundesland, null, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("P_Bundesland", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.P_Bundesland, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KlinikApp_WebApplication3/Views/Patients/Delete.cshtml
@model KlinikApp_WebApplication3.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Plz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Plz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bundesland.B_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bundesland.B_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KlinikApp_WebApplication3/Views/Patients/Details.cshtml
@model KlinikApp_WebApplication3.Models.Patient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Plz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Plz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bundesland.B_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bundesland.B_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Pat_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KlinikApp_WebApplication3/Views/Patients/Edit.cshtml
@model KlinikApp_WebApplication3.Models.Patient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*Html.HiddenFor(model => model.Pat_Id)*@

        <div class="form-group">
            @Html.LabelFor(model => model.P_Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Plz, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Plz, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Plz, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Bundesland, null, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("P_Bundesland", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.P_Bundesland, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KlinikApp_WebApplication3/Views/Patients/Index.cshtml
@model IEnumerable<KlinikApp_WebApplication3.Models.Patient>

@{
    ViewBag.Title = "Index";
}
<h2>Patients</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@using (Ajax.BeginForm("PatientSearch", "Patients",
           new AjaxOptions
           {
               InsertionMode = InsertionMode.Replace,
               HttpMethod = "POST",

               UpdateTargetId = "patientTable",
           }))
{
    
    <input id="searchField" type="text" name="searchPatient" value="@ViewBag.patientsearch" placeholder="Search" />
    <input type="submit" value="Search" />
}


@Html.Partial("_patients", Model)


@section Scripts {

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

@*<script>
    $("#searchField").keyup(function () {
        var searchText = $("#searchField").val();
        $.ajax({
            type: "POST",
            url: "Patients/PatientSearch",

            UpdateTargetId = "patientTable"
        });

    });
</script>*@

KlinikApp_WebApplication3/Views/Patients/_patients.cshtml
@model IEnumerable<KlinikApp_WebApplication3.Models.Patient>

@*partieller View für die Patientliste in index.cshtml*@
<div id="patientTable">
    <table class="table">
        <tr>
            <th>
                @Ajax.ActionLink("Lastname", "PatientSearch", "Patients", new { sortOrder = ViewBag.LastnameSortParm},
                new AjaxOptions {
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "patientTable"
                })
                @*@Html.DisplayNameFor(model => model.P_Lastname)*@
            <th>
                @Ajax.ActionLink("Firstname", "PatientSearch", "Patients", new { sortOrder = ViewBag.FirstnameSortParm },
                new AjaxOptions
                     {
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "patientTable"
                })
                @*@Html.ActionLink("Firstname", "PatientSearch", new { sortOrder = ViewBag.FirstnameSortParm })*@
                @*@Html.DisplayNameFor(model => model.P_Firstname)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.P_Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.P_Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.P_Plz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bundesland.B_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NrOfExams)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.P_Lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.P_Firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.P_Birthday)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.P_Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.P_Plz)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bundesland.B_Name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.NrOfExams)
        </td>*@
        <td>
            @{
                foreach (var exam in item.Examinations)
                {
                    @exam.Examtype.Exty_Name <br />
                }
            }
        </td>
        <td>
            @Html.ActionLink("Examinations", "Index", "Examinations", new { id = item.Pat_Id.ToString(), lastname = item.P_Lastname, type = "patient" }, null) |
            @Html.ActionLink("Edit", "Edit", new { id = item.Pat_Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Pat_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Pat_Id })
        </td>
    </tr>
        }

    </table>
</div>